### ISSUE TITLE
hi，偶然逛到这里，有几个问题想请教楼主，多谢

### ISSUE THREAD

**Issue by whiteguo233** [arition/Bangumi-Api#1]
最近想做个Android版的bangumi客户端练手，偶然看到这个api，有几个问题想问下：
1. basic 64编码是否就是base64编码
2. 请求的时候 是否是简单的 post form 提交的形式  
Authorization  = Basic {MzzcwTk4QHFxLmNvbQ==:Z3N5OTzAy}
试了下 一直提示wrong pass 希望能帮忙解答下，多谢

**Comment by arition** [comment]
嗯当时有些东西写的比较混乱，刚刚改掉了w  
关于Authoriation头的话，是这样子的  
如果你的用户名是 littlewish，密码是123456的话 编码是`base64("liitlewish:123456")`这样子的  
提交的header应该是`Authorization = Basic bGlpdGxld2lzaDoxMjM0NTY=`这样  
这个Authorization头是http的标准，你可以参考一下[维基](https://zh.wikipedia.org/wiki/HTTP%E5%9F%BA%E6%9C%AC%E8%AE%A4%E8%AF%81)

**Comment by whiteguo233** [comment]
多谢，刚又试了下，直接500了，这个服务器是有问题么。。。，话说这个api是怎么摸出来的？

**Comment by whiteguo233** [comment]
又试了下，可以了，多谢，不过这个api 也太不健壮了。。。。

**Comment by arition** [comment]
解决了就好
